/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteRouteImport } from './routes/index.route'
import { Route as DrinksCreateRouteRouteImport } from './routes/drinks.create.route'
import { Route as DrinksDrinkSlugRouteRouteImport } from './routes/drinks.$drinkSlug.route'

const IndexRouteRoute = IndexRouteRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DrinksCreateRouteRoute = DrinksCreateRouteRouteImport.update({
  id: '/drinks/create',
  path: '/drinks/create',
  getParentRoute: () => rootRouteImport,
} as any)
const DrinksDrinkSlugRouteRoute = DrinksDrinkSlugRouteRouteImport.update({
  id: '/drinks/$drinkSlug',
  path: '/drinks/$drinkSlug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRouteRoute
  '/drinks/$drinkSlug': typeof DrinksDrinkSlugRouteRoute
  '/drinks/create': typeof DrinksCreateRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRouteRoute
  '/drinks/$drinkSlug': typeof DrinksDrinkSlugRouteRoute
  '/drinks/create': typeof DrinksCreateRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRouteRoute
  '/drinks/$drinkSlug': typeof DrinksDrinkSlugRouteRoute
  '/drinks/create': typeof DrinksCreateRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/drinks/$drinkSlug' | '/drinks/create'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/drinks/$drinkSlug' | '/drinks/create'
  id: '__root__' | '/' | '/drinks/$drinkSlug' | '/drinks/create'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRouteRoute: typeof IndexRouteRoute
  DrinksDrinkSlugRouteRoute: typeof DrinksDrinkSlugRouteRoute
  DrinksCreateRouteRoute: typeof DrinksCreateRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drinks/create': {
      id: '/drinks/create'
      path: '/drinks/create'
      fullPath: '/drinks/create'
      preLoaderRoute: typeof DrinksCreateRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drinks/$drinkSlug': {
      id: '/drinks/$drinkSlug'
      path: '/drinks/$drinkSlug'
      fullPath: '/drinks/$drinkSlug'
      preLoaderRoute: typeof DrinksDrinkSlugRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRouteRoute: IndexRouteRoute,
  DrinksDrinkSlugRouteRoute: DrinksDrinkSlugRouteRoute,
  DrinksCreateRouteRoute: DrinksCreateRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
